-- -----------------------------------------------------
-- Deletar tabelas se existirem
-- -----------------------------------------------------
begin
   execute immediate 'DROP TABLE itens_compra CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE compras CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE itens_carrinho CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE produtos CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE fabricante CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE subcategoria CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE categoria CASCADE CONSTRAINTS';
   execute immediate 'DROP TABLE cliente CASCADE CONSTRAINTS';
exception
   when others then
      null; -- Ignorar erros caso as tabelas não existam
end;
/

-- -----------------------------------------------------
-- Deletar triggers se existirem
-- -----------------------------------------------------
begin
   execute immediate 'DROP TRIGGER verificar_valor_total';
   execute immediate 'DROP TRIGGER atualizar_valor_total_compra';
   execute immediate 'DROP TRIGGER chk_data_compra_valida';
exception
   when others then
      null; -- Ignorar erros caso as triggers não existam
end;
/

-- -----------------------------------------------------
-- Recriar as tabelas e triggers
-- -----------------------------------------------------
-- Criar a tabela cliente
create table cliente (
   id_cliente number
      generated by default as identity
   primary key,
   cpf        char(11) not null,
   nome       varchar2(100) not null,
   email      varchar2(100) not null,
   senha      varchar2(255) not null,
   constraint uk_email unique ( email ),
   constraint uk_cpf unique ( cpf ),
   constraint chk_cpf_valido check ( regexp_like ( cpf,
                                                   '^[0-9]{11}$' ) ),
   constraint chk_email_valido check ( regexp_like ( email,
                                                     '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,63}$' ) ),
   constraint chk_senha_valida check ( length(senha) >= 8 )
);

-- Criar a tabela categoria
create table categoria (
   id_categoria number
      generated by default as identity
   primary key,
   nome         varchar2(45) not null,
   constraint uk_categoria unique ( nome )
);

-- Criar a tabela subcategoria
create table subcategoria (
   id_subcategoria number
      generated by default as identity
   primary key,
   nome            varchar2(45) not null,
   id_categoria    number not null,
   constraint uk_subcategoria unique ( nome ),
   constraint fk_subcategoria_categoria foreign key ( id_categoria )
      references categoria ( id_categoria )
         on delete cascade
);

-- Criar a tabela fabricante
create table fabricante (
   id_fabricante number
      generated by default as identity
   primary key,
   nome          varchar2(100) not null,
   constraint uk_fabricante unique ( nome )
);

-- Criar a tabela produtos
create table produtos (
   id_produtos        number
      generated by default as identity
   primary key,
   nome               varchar2(100) not null,
   preco              number(10,2) not null check ( preco > 0 ),
   quantidade_estoque number not null check ( quantidade_estoque >= 0 ),
   descricao          clob,
   id_subcategoria    number not null,
   id_fabricante      number not null,
   constraint fk_produtos_subcategoria foreign key ( id_subcategoria )
      references subcategoria ( id_subcategoria )
         on delete cascade,
   constraint fk_produtos_fabricante foreign key ( id_fabricante )
      references fabricante ( id_fabricante )
         on delete cascade
);

-- Criar a tabela itens_carrinho
create table itens_carrinho (
   id_cliente  number not null,
   id_produtos number not null,
   quantidade  number not null check ( quantidade >= 0 ),
   primary key ( id_cliente,
                 id_produtos ),
   constraint fk_itens_carrinho_cliente foreign key ( id_cliente )
      references cliente ( id_cliente )
         on delete cascade,
   constraint fk_itens_carrinho_produtos foreign key ( id_produtos )
      references produtos ( id_produtos )
);

-- Criar a tabela compras
create table compras (
   id_compras  number
      generated by default as identity
   primary key,
   id_cliente  number not null,
   data_compra date not null,
   valor_total number(10,2) not null check ( valor_total > 0 ),
   constraint fk_compras_cliente foreign key ( id_cliente )
      references cliente ( id_cliente )
         on delete cascade
);

-- Criar o trigger chk_data_compra_valida
create or replace trigger chk_data_compra_valida before
   insert or update on compras
   for each row
begin
   if :new.data_compra > sysdate then
      raise_application_error(
         -20001,
         'A data da compra não pode ser no futuro.'
      );
   end if;
end;
/

-- Criar a tabela itens_compra
create table itens_compra (
   id_compras     number not null,
   id_cliente     number not null,
   id_produtos    number not null,
   quantidade     number not null check (quantidade > 0),
   preco_unitario number(10,2) not null check (preco_unitario > 0 ),
   primary key ( id_compras, id_produtos, id_cliente ),
   constraint fk_itens_compra_compras
      foreign key ( id_compras )
         references compras ( id_compras )
         on delete cascade,
   constraint fk_itens_compra_produtos foreign key ( id_produtos )
      references produtos ( id_produtos )
);


-- Criar o trigger verificar_valor_total
create or replace trigger verificar_valor_total after
   insert or update on compras
   for each row
declare
   soma_itens number(
      10,
      2
   );
begin
   select sum(preco_unitario * quantidade)
     into soma_itens
     from itens_compra
    where id_compras = :new.id_compras
      and id_cliente = :new.id_cliente;

   if soma_itens != :new.valor_total then
      raise_application_error(
         -20001,
         'O valor total informado ('
         || :new.valor_total
         || ') não corresponde à soma dos itens ('
         || soma_itens
         || ')'
      );
   end if;
end;
/

-- Criar o trigger atualizar_valor_total_compra
create or replace trigger atualizar_valor_total_compra after
   insert or update or delete on itens_compra
   for each row
begin
   update compras
      set
      valor_total = (
         select sum(quantidade * preco_unitario)
           from itens_compra
          where id_compras = :new.id_compras
            and id_cliente = :new.id_cliente
      )
    where id_compras = :new.id_compras
      and id_cliente = :new.id_cliente;
end;
/